[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "/usr/local/bin/zellij", args = [
  "options",
  "--scroll-buffer-size",
  "100000",
] }

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
blur = true
opacity = 0.9
option_as_alt = "Both"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[scrolling]
history = 100000
