[env]
TERM = "xterm-256color"

# [terminal]
# shell = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "Buttonless"
blur = true
opacity = 0.9

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
